Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
  end

  config.vm.define "awx" do |m|
      m.vm.network "private_network", ip: "192.168.0.201"
      m.vm.provision "shell", path: "setup.sh"
      m.vm.hostname = "awx"
  end

end
