- name: Create EC2 Instante
  local_action: 
    module: ec2
    group: "{{ sec_group_name }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    key_name: "{{ key_name }}"
    count: "{{ instance_count }}"
    wait: yes
    #assign_public_ip: yes
  register: ec2
    
- name: Add Host Address to Inventory
  add_host: 
    name: "{{ item.public_ip }}"
    groups: giropops
  with_items: "{{ ec2.instances }}"
- name: Add Public IP to Hosts
  local_action: 
    module: lineinfile
    path: ./hosts 
    regex: "{{ item.public_ip }}"
    insertafter: "[cluster]" 
    line: "{{ item.public_ip }}"
  with_items: "{{ ec2.instances }}"
- name: Add Private IP to Hosts
  local_action: 
    module: lineinfile
    path: ./hosts 
    regex: "{{ item.private_ip }}"
    insertafter: "[ansible ]" 
    line: "{{ item.private_ip }}"
  with_items: "{{ ec2.instances }}"

- name: Waiting SSH
  local_action:
    module: wait_for
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"

- name: Adding a tag to EC2 Instance
  local_action: 
    module: ec2_tag
    resource: "{{ item.id }}"
    region: "{{ region }}"
    profile: "{{ profile }}"
    state: present
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Name: ansible-{{ item.ami_launch_index|int + 1 }}